{"name": "test_auth_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert 403 in [401, 400]\n +  where 403 = <Response [403]>.status_code", "trace": "self = <test_auth_api.TestAuthAPI object at 0x104a387f0>\n\n    def test_auth_failure(self):\n        \"\"\"Test failed authentication\"\"\"\n        response = self.client.post(\n            f\"{self.client.base_url}{BASE_PATH}\",\n            json={\"username\": \"admin\", \"password\": \"wrongpassword\"}\n        )\n>       assert response.status_code in [401, 400]\nE       assert 403 in [401, 400]\nE        +  where 403 = <Response [403]>.status_code\n\ntests/test_auth_api.py:29: AssertionError"}, "description": "Test failed authentication", "start": 1750257937005, "stop": 1750257937059, "uuid": "e26187b9-47a8-4a19-a329-36a123e241c6", "historyId": "7ec695e0f8762b2cb3ff9c654ebd0b5d", "testCaseId": "7ec695e0f8762b2cb3ff9c654ebd0b5d", "fullName": "tests.test_auth_api.TestAuthAPI#test_auth_failure", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_auth_api"}, {"name": "subSuite", "value": "TestAuthAPI"}, {"name": "host", "value": "Rs-MacBook-Pro-2.local"}, {"name": "thread", "value": "56688-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_auth_api"}]}